### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by pt1602** [FriendsOfShopware/FroshPlatformTemplateMail#2]
It would be great to have a slightly better documentation for this plugin. For my case, I created the folder with the needed files but nothing changes.

Here my created path: 

`shopware⁩ ▸ ⁨custom⁩ ▸ ⁨plugins⁩ ▸ ⁨THEME ▸ ⁨src⁩ ▸ ⁨Resources⁩ ▸ ⁨views⁩ ▸ ⁨email⁩ ▸ ⁨global⁩ ▸ ⁨order_transaction.state.paid⁩ `

Or do I miss anything?

**Comment by mathiassname** [comment]
Please, add a simple attention, that the mail template don't work from the admin area.

**Comment by shyim** [comment]
Could you test it again against the master branch?
Even administration mails should now work.

**Comment by shyim** [comment]
@pt1602 
Your path is wrong it should work with
```src/Resources/views/email/global/order_transaction.state.paid/html.twig```

**Comment by pt1602** [comment]
Got it working when testing from the frontend. Gonna checkout the new master now and will give you feedback. Thanks!

**Comment by pt1602** [comment]
Hey tested it and for me it still wont work, if I send a test mail from here:

![image](https://user-images.githubusercontent.com/57329320/73437077-fcbbdd80-434b-11ea-8f84-778cfa6ecf16.png)

I still get the mail, wich is configured on the left and not my custom template.

**Comment by shyim** [comment]
You have to trigger the mail in real way and not using Test-Mail button

**Comment by vardumper** [comment]
> @pt1602
> Your path is wrong it should work with
> `src/Resources/views/email/global/order_transaction.state.paid/html.twig`

then the path in the readme examples is wrong.
